# Generated by Django 5.2.8 on 2025-11-16 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=100, verbose_name='название меню')),
                ('title', models.CharField(max_length=200, verbose_name='название пункта')),
                ('url', models.CharField(blank=True, max_length=200, verbose_name='URL')),
                ('order', models.IntegerField(default=0, verbose_name='порядок сортировки')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.menuitem', verbose_name='родительский пункт')),
            ],
            options={
                'verbose_name': 'пункт меню',
                'verbose_name_plural': 'пункты меню',
                'ordering': ['menu_name', 'order', 'id'],
                'indexes': [models.Index(fields=['menu_name'], name='menu_menuit_menu_na_afda77_idx')],
            },
        ),
    ]
