# Generated by Django 5.2.8 on 2025-11-16 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['order', 'id'], 'verbose_name': 'пункт меню', 'verbose_name_plural': 'пункты меню'},
        ),
        migrations.RemoveIndex(
            model_name='menuitem',
            name='menu_menuit_menu_na_afda77_idx',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='menu_name',
        ),
    ]
